/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.21).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.ibm.bbsrv.controller;

import com.ibm.bbsrv.exception.BedBookingPatientException;
import com.ibm.bbsrv.exception.CustomException;
import com.ibm.bbsrv.exception.PatientPendingException;
import com.ibm.bbsrv.model.AutoConfirmRequest;
import com.ibm.bbsrv.model.BedBookingStatusResponse;
import com.ibm.bbsrv.model.BookingConfirmRequest;
import com.ibm.bbsrv.model.BookingConfirmResponse;
import com.ibm.bbsrv.model.BookingResponse;
import com.ibm.bbsrv.model.BookingUserData;

public interface BbsApi {

	BookingConfirmResponse confirmBooking(String xTokenID, String bookingId, BookingConfirmRequest bookingUserData) throws CustomException;

	Boolean deleteBooking(String xTokenID, String bookingId);

	BedBookingStatusResponse getBookingStatus(String xTokenID, String bookingId) throws CustomException;

	BookingResponse reserveBed(String xTokenID, BookingUserData bookingUserData) throws CustomException, PatientPendingException, BedBookingPatientException;

	void autoConfirm(String xTokenID, AutoConfirmRequest autoConfirmRequest) throws CustomException;
}