spring.cloud.stream:
  function:
    definition: autoConfirm
  bindings:
    autoConfirm-in-0:
      destination: hospitalBeds
  kafka:
    bindings:
      autoConfirm-in-0:
        consumer:
          configuration:
            value:
              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    binders:
      brokers:
        - localhost:9092